name: chat
version: 'beta-0.1.1'
main: org.sirchickenix.chat.Main
api-version: '1.21'
authors: [ SirChickenIX ]
description: This plugin allows chat to be toggled on and off
depend: [ LuckPerms ]
commands:
  chat:
    description: Access settings for chat
    usage: /<command> to open gui
permissions:
  chat.chat:
    description: Allows someone to run the /chat command
    default: op