name: chat
version: '1.0-SNAPSHOT'
main: org.sirchickenix.chat.Main
api-version: '1.21'
authors: [ SirChickenIX ]
commands:
  chat:
    description: Access settings for chat
    usage: /<command>
    permission: simplechat.chat
    permission-message: You don't have permission to run this command
permissions:
  simplechat.chat:
    description: Allows someone to run the /chat command
    default: op