name: chat
version: '1.0-SNAPSHOT'
main: org.sirchickenix.chat.Main
api-version: '1.21'
authors: [ SirChickenIX ]
commands:
  chat:
    description: Access settings for chat
    usage: /<command> to open gui
    permission: "simplechat.chat"
permissions:
  simplechat.chat:
    description: Allows someone to run the /chat command
    default: op